### ISSUE TITLE
Change default stylesheet display text for <dao> objects.

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/findingaids#1]
Due to patron confusion, we would like to replace the "Reading Room access only" display text on <dao> objects to "Digital/digitized copy available in the Reading Room". This is a stylesheet change within the <dao> element.

**Comment by rosy1280** [comment]
Has this already been completed? See https://findingaids.library.emory.edu/documents/nunn823/?keywords=sam

**Comment by alexBLR** [comment]
@rosy1280 not sure.

**Comment by erussey** [comment]
Documenting that this story was complete and mistakenly added to the board.
