### ISSUE TITLE
Wildcard search not highlighting in search results

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/findingaids#2]

**Comment by rosy1280** [comment]
search highlights the words that are identified, but with wildcards the "reason" you got a search isn't highlighted.  this used to work, and now doesn't.

@erussey to provide examples here.

analysis pending resolution

**Comment by erussey** [comment]
The wildcard search in Emory Finding Aids is not working correctly. If you search for a term using or ?, the search engine will find documents or words within documents containing the correct results, but it won't highlight them properly. For an example, try searching for "photograph*" vs. photograph. When a finding aid result is returned, matched words should highlight in red. They aren't doing that for the wildcard results.

**Comment by rosy1280** [comment]
- [x] search for a term using * OR ?, the search engine will highlight words within documents containing the results
- [x] highlight should be in red

**Comment by erussey** [comment]
@alexBLR .  I'm getting an attribute error when I try to open any search result:  "Error during template rendering.  ArchivalDescription object has no attribute 'appraisal'.  Looks like I might be blocked from testing any EFA stories until the appraisal story is done @rosy1280 .

**Comment by alexBLR** [comment]
unblocked and fixed the issue. @erussey You can test it now.

**Comment by erussey** [comment]
@alexBLR : This isn't working.  If you try a search for "book" in test, look for the black print culture collection, and click into a series.  You can see the word highlighted in the series container list:  https://testfindingaids.library.emory.edu/documents/blackprintculture921/series1/?keywords=book  If you try this same search using "book*" and click into the same result, it's not working: https://testfindingaids.library.emory.edu/documents/blackprintculture921/?keywords=book%2A
