### ISSUE TITLE
Diacritical searching is not working

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/findingaids#3]

**Comment by rosy1280** [comment]
diacritics aren't being indexed and the words can't be searched on

**Comment by rosy1280** [comment]
- [ ] run scripts for indexing
- [ ] analysis (pending resolution)

**Comment by erussey** [comment]
Example with diacritic in title and creator:  http://pid.emory.edu/ark:/25593/gs69x
Example with diacritic in container list (Césaire): http://pid.emory.edu/ark:/25593/8z8xr

**Comment by rotated8** [comment]
Closing as won't fix, with the move to ASpace.
