### ISSUE TITLE
Add <appraisal> to the list of display tags

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/findingaids#4]

**Comment by rosy1280** [comment]
- [ ] update stylesheet to make appraisal tag appear

**Comment by erussey** [comment]
A new EAD tag needs to be added to the finding aids display. It should appear after Citation and before Processing at the collection level and the series/subseries level (@level=series) (@level=subseries). Example documents for testing with the new tag are in test (svn: EAD_Dev-MARBL): tretheway1272, clum1401. Clum has the tag at the collection level. Tretheway has the tag at the collection and series level (series 7). If it helps, the <arrangement> tag should have similar display rules and could be followed to add the <appraisal> tag (it displays at all levels of the finding aid except the box level).

**Comment by alexBLR** [comment]
Requires a release of eulxml package @rosy1280

**Comment by erussey** [comment]
Testing complete...looks good.
