### ISSUE TITLE
Wildcard search series, subseries

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/findingaids#5]
As a product owner, I want to see a wildcard search results highlighted in red when viewing series and subseries of findingaids

**Comment by erussey** [comment]
@alexBLR : Actually, this is when viewing all levels of finding aids.  A couple of collections like Ted Hughes and Alice Walker go into subsubseries.

**Comment by rotated8** [comment]
Closing as won't fix, with the move to ASpace
