### ISSUE TITLE
Finding Aids with numbers beginning <origination> will not load.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/findingaids#6]
One of our finding aids (woodham800east1419) will not load into EFA.  We are receiving the following error message: "First letter ('8') of list title field origination/corpname does not match browse letter URL regex '[a-zA-Z]."

Essentially we need the browse index to support numerical characters as well as letters in cases where the <origination><corpname> includes them.  This shouldn't be a problem for <persname> or <famname>, which wouldn't begin with a numerical character.

**Comment by rotated8** [comment]
Closing as won't fix, with move to ASpace.
