### ISSUE TITLE
TestFindingAids Migration

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/findingaids#9]
The TestFindingAids application lives on the same server as TestOpenEmory, which requires a specific Apache module with a specific Python version that conflicts with TestFindingAids. In order to provide a TestFindingAids application, we will move it to the same server that hosts the production FindingAids, but continue to use the connections to the other testing infrastructure.

- [x] @alexBLR - Ensure the connections for QA background services work to the prod server (see below)
- [x] @alexBLR - Backup/extract current configuration from test
- [x] @jcrompton42 @kbowaterskelly - Create new Apache site on the prod server
- [x] @alexBLR - Create a new test FindingAids app on the production server, add the test config
- [x] @kbowaterskelly - Move DNS from the test server to the new application.
- [ ] @rotated8 - Communicate status and updates with stakeholder

---

Background services FindingAids uses:
- ExistDB
- PidMan
- SVN (mount?) maybe a different mount for QA
- Solr
- RabbitMQ
- MYSQL database

**Comment by jcrompton42** [comment]
New apache configuration for testfindingaids created, along with new user testfiningaids and folder /home/httpd/testfindingaids on server webprd003

**Comment by kbowaterskelly** [comment]
New cert requested and DNS change ordered

**Comment by kbowaterskelly** [comment]
Validated DNS change and certificate

**Comment by alexBLR** [comment]
Hey @jcrompton42 webprd003 can't connect to "Can't connect to MySQL server on 'libmysqldev1.cc.emory.edu'"
Would you be able to contact the DB team about it.

**Comment by jcrompton42** [comment]
@alexBLR on it

**Comment by jcrompton42** [comment]
Requesting firewall exception for libmysqldev1 from webprd003

**Comment by jcrompton42** [comment]
@alexBLR testfindingaids should be able to connect to libmysqldev1 using the same passowrd now

**Comment by kbowaterskelly** [comment]
Sorry, not clear on what needs to happen to kick on that apache configuration for testfindingaids, looks like maybe it needs to have content copied over. Let's look at this early next week.

**Comment by alexBLR** [comment]
@jcrompton42 getting this error on testfindingaids: "Access denied for user 'findingaids'@'webprd003.library.emory.edu' (using password: YES)" Similar to what we had with Open Emory.

**Comment by jcrompton42** [comment]
testfindingaids is currently reachable with errors, so...progress. We have some issues of having both prod and test on one server to sort.

**Comment by jcrompton42** [comment]
testfindingaids is up and working! @rotated8 please notify the customer?

**Comment by rotated8** [comment]
Done and accepted by the customer.
